# Токен для бота в телеграме
API_TOKEN: 'YOUR TOKEN'

# Период, на который будет доступно бронирование парковочных мест
RESERVATION_PERIOD_DAYS: 4

# Имена для парковочных мест.
# Можно придумать осмысленные значения.
# Можно указать код/номер.
PARKING_SPOTS: ["А01", "А02", "B04"]

# Имя базы данных SQLite, где будет храниться вся информация
DB_NAME: "parking_spots.db"

# Список администраторов, которые могут выгружать отчёты по использованию парковочных мест
ADMINISTRATORS: ["VladimirPn", "SomeName1"]